/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Season, SubscribedFeed, SubscriptionStatus, } from "./models";
export namespace Components {
    interface AfmCard {
        "feedInfo": SubscribedFeed;
        "subscriptionStatus": SubscriptionStatus;
    }
    interface AfmHome {
        "season": Season;
        "year": string;
    }
    interface AfmMailSelector {
    }
    interface AfmNav {
    }
    interface AfmRoot {
    }
}
declare global {
    interface HTMLAfmCardElement extends Components.AfmCard, HTMLStencilElement {
    }
    var HTMLAfmCardElement: {
        prototype: HTMLAfmCardElement;
        new (): HTMLAfmCardElement;
    };
    interface HTMLAfmHomeElement extends Components.AfmHome, HTMLStencilElement {
    }
    var HTMLAfmHomeElement: {
        prototype: HTMLAfmHomeElement;
        new (): HTMLAfmHomeElement;
    };
    interface HTMLAfmMailSelectorElement extends Components.AfmMailSelector, HTMLStencilElement {
    }
    var HTMLAfmMailSelectorElement: {
        prototype: HTMLAfmMailSelectorElement;
        new (): HTMLAfmMailSelectorElement;
    };
    interface HTMLAfmNavElement extends Components.AfmNav, HTMLStencilElement {
    }
    var HTMLAfmNavElement: {
        prototype: HTMLAfmNavElement;
        new (): HTMLAfmNavElement;
    };
    interface HTMLAfmRootElement extends Components.AfmRoot, HTMLStencilElement {
    }
    var HTMLAfmRootElement: {
        prototype: HTMLAfmRootElement;
        new (): HTMLAfmRootElement;
    };
    interface HTMLElementTagNameMap {
        "afm-card": HTMLAfmCardElement;
        "afm-home": HTMLAfmHomeElement;
        "afm-mail-selector": HTMLAfmMailSelectorElement;
        "afm-nav": HTMLAfmNavElement;
        "afm-root": HTMLAfmRootElement;
    }
}
declare namespace LocalJSX {
    interface AfmCard {
        "feedInfo"?: SubscribedFeed;
        "onSubscriptionSelected"?: (event: CustomEvent<string>) => void;
        "onUnsubscriptionSelected"?: (event: CustomEvent<string>) => void;
        "subscriptionStatus"?: SubscriptionStatus;
    }
    interface AfmHome {
        "season"?: Season;
        "year"?: string;
    }
    interface AfmMailSelector {
        "onEmailSelected"?: (event: CustomEvent<string>) => void;
    }
    interface AfmNav {
    }
    interface AfmRoot {
    }
    interface IntrinsicElements {
        "afm-card": AfmCard;
        "afm-home": AfmHome;
        "afm-mail-selector": AfmMailSelector;
        "afm-nav": AfmNav;
        "afm-root": AfmRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "afm-card": LocalJSX.AfmCard & JSXBase.HTMLAttributes<HTMLAfmCardElement>;
            "afm-home": LocalJSX.AfmHome & JSXBase.HTMLAttributes<HTMLAfmHomeElement>;
            "afm-mail-selector": LocalJSX.AfmMailSelector & JSXBase.HTMLAttributes<HTMLAfmMailSelectorElement>;
            "afm-nav": LocalJSX.AfmNav & JSXBase.HTMLAttributes<HTMLAfmNavElement>;
            "afm-root": LocalJSX.AfmRoot & JSXBase.HTMLAttributes<HTMLAfmRootElement>;
        }
    }
}
