using System;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AnimeFeedManager.SourceGenerators.HyperscriptScripts;

/// <summary>
/// Compiles colocated <c>*.razor.hs</c> files into Blazor partial classes
/// containing a <c>private const string Script</c> field. The const can then
/// be referenced from the paired <c>.razor</c> file as <c>_="@Script"</c>,
/// which works around the RZ9986 Razor parser trap on Blazor component
/// attributes while preserving editor tooling for hyperscript content.
/// </summary>
[Generator]
public class HyperscriptScriptsGenerator : IIncrementalGenerator
{
    private const string FileExtension = ".razor.hs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pipeline = context.AdditionalTextsProvider
            .Where(static t => t.Path.EndsWith(FileExtension, StringComparison.OrdinalIgnoreCase))
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, ct) =>
            {
                var text = pair.Left;
                var options = pair.Right;

                var fileOptions = options.GetOptions(text);
                fileOptions.TryGetValue("build_metadata.AdditionalFiles.RelativeDir", out var relativeDir);
                options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);

                var content = text.GetText(ct)?.ToString() ?? string.Empty;

                return (
                    Path: text.Path,
                    RelativeDir: relativeDir ?? string.Empty,
                    RootNamespace: rootNamespace ?? string.Empty,
                    Content: content);
            });

        context.RegisterSourceOutput(pipeline, static (spc, info) => Emit(spc, info));
    }

    private static void Emit(
        SourceProductionContext context,
        (string Path, string RelativeDir, string RootNamespace, string Content) info)
    {
        if (string.IsNullOrEmpty(info.RootNamespace))
            return;

        var fileName = Path.GetFileName(info.Path);
        var className = StripExtension(fileName);
        if (string.IsNullOrEmpty(className))
            return;

        var namespaceSuffix = NormalizeRelativeDir(info.RelativeDir);
        var fullNamespace = string.IsNullOrEmpty(namespaceSuffix)
            ? info.RootNamespace
            : info.RootNamespace + "." + namespaceSuffix;

        var hintName = string.IsNullOrEmpty(namespaceSuffix)
            ? className + ".HyperscriptScript.g.cs"
            : namespaceSuffix + "." + className + ".HyperscriptScript.g.cs";

        var source = BuildSource(fullNamespace, className, info.Content);
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string StripExtension(string fileName)
    {
        return fileName.EndsWith(FileExtension, StringComparison.OrdinalIgnoreCase)
            ? fileName.Substring(0, fileName.Length - FileExtension.Length)
            : fileName;
    }

    private static string NormalizeRelativeDir(string relativeDir)
    {
        if (string.IsNullOrEmpty(relativeDir))
            return string.Empty;

        var normalized = relativeDir.Replace('\\', '.').Replace('/', '.');
        return normalized.Trim('.');
    }

    private static string BuildSource(string fullNamespace, string className, string content)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(fullNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("partial class ").AppendLine(className);
        sb.AppendLine("{");

        if (string.IsNullOrEmpty(content))
        {
            sb.AppendLine("    private const string Script = \"\";");
        }
        else
        {
            var quoteCount = SafeRawStringQuoteCount(content);
            var delimiter = new string('"', quoteCount);

            sb.Append("    private const string Script = ").AppendLine(delimiter);
            sb.AppendLine(content.TrimEnd('\r', '\n'));
            sb.Append(delimiter).AppendLine(";");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static int SafeRawStringQuoteCount(string content)
    {
        var longestRun = 0;
        var currentRun = 0;

        foreach (var ch in content)
        {
            if (ch == '"')
            {
                currentRun++;
                if (currentRun > longestRun)
                    longestRun = currentRun;
            }
            else
            {
                currentRun = 0;
            }
        }

        return Math.Max(3, longestRun + 1);
    }
}
