global using AnimeFeedManager.Features.AniDb;
global using AnimeFeedManager.Common.Dto;
global using AnimeFeedManager.Common.Types;
global using AnimeFeedManager.Features.Images;
global using AnimeFeedManager.Features.Infrastructure;
global using AnimeFeedManager.Features.State;
global using AnimeFeedManager.Features.Tv;
global using AnimeFeedManager.Features.Movies;
global using AnimeFeedManager.Features.Ovas;
global using AnimeFeedManager.Common.Domain;
global using AnimeFeedManager.Common.Domain.Notifications;
global using AnimeFeedManager.Features.Notifications;
global using AnimeFeedManager.Features.Seasons;
global using AnimeFeedManager.Web.BlazorComponents;
global using Microsoft.Azure.Functions.Worker;
global using System.Text.Json;
global using LanguageExt;
global using static LanguageExt.Prelude;