/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AfmNav {}
  interface AfmRoot {}
  interface AppHome {}
  interface AppProfile {
    'name': string;
  }
}

declare global {


  interface HTMLAfmNavElement extends Components.AfmNav, HTMLStencilElement {}
  var HTMLAfmNavElement: {
    prototype: HTMLAfmNavElement;
    new (): HTMLAfmNavElement;
  };

  interface HTMLAfmRootElement extends Components.AfmRoot, HTMLStencilElement {}
  var HTMLAfmRootElement: {
    prototype: HTMLAfmRootElement;
    new (): HTMLAfmRootElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    'afm-nav': HTMLAfmNavElement;
    'afm-root': HTMLAfmRootElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
  }
}

declare namespace LocalJSX {
  interface AfmNav {}
  interface AfmRoot {}
  interface AppHome {}
  interface AppProfile {
    'name'?: string;
  }

  interface IntrinsicElements {
    'afm-nav': AfmNav;
    'afm-root': AfmRoot;
    'app-home': AppHome;
    'app-profile': AppProfile;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'afm-nav': LocalJSX.AfmNav & JSXBase.HTMLAttributes<HTMLAfmNavElement>;
      'afm-root': LocalJSX.AfmRoot & JSXBase.HTMLAttributes<HTMLAfmRootElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
    }
  }
}


