global using AnimeFeedManager.Features.Infrastructure.TableStorage;
global using AnimeFeedManager.Shared.Results;
global using AnimeFeedManager.Shared.Results.Static;
global using AnimeFeedManager.Shared.Results.Errors;
global using AnimeFeedManager.Web.Features.Components.Badge;
global using AnimeFeedManager.Web.Features.Components.Responses;
global using AnimeFeedManager.Web.Features.Security;
global using AnimeFeedManager.Web.Htmx;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc;
global using static AnimeFeedManager.Web.Common.Validation.ValidationHelpers;